CREATE TABLE `hackathon`.`DRIVER` (
  `LICENSE` CHAR(9) NOT NULL,
  `KAKAO_ID` INT NULL,
  `CAR_MODEL` VARCHAR(50) NULL,
  `name` VARCHAR(50) NULL,
  `CAR_NUMBER` VARCHAR(10) NULL,
  `BUSINESS_NUMBER` CHAR(10) NULL,
  `ADDRESS_MAIN` VARCHAR(100) NULL,
  `ADDRESS_SUB` VARCHAR(100) NULL,
  `ZIP_COD` VARCHAR(8) NULL,
  `SIDO` VARCHAR(10) NULL,
  `SIGUNGU` VARCHAR(10) NULL,
  `LET` DECIMAL(14,3) NULL,
  `LONG` DECIMAL(14,3) NULL,
  `PHONE_NUMBER` VARCHAR(10) NULL,
  `COMPANNY` VARCHAR(45) NULL,
  PRIMARY KEY (`LICENSE`)
) DEFAULT CHARACTER SET = DEFAULT;
